language: java
sudo: false

cache:
  apt: true
  directories:
    - ~/.m2

branches:
  only:
    - master

install:
  - ""

matrix:
  fast_finish: true
  include:
    - jdk: openjdk8
      env:
        - DESC="install (openjdk8)"
        - CMD="mvn install && git diff"

    - jdk: openjdk11
      env:
        - DESC="install (openjdk11)"
        - CMD="mvn install && git diff"

    - jdk: openjdk12
      env:
        - DESC="install (openjdk12)"
        - CMD="mvn install && git diff"

script:
  - |
     echo "eval of CMD is starting";
     echo "CMD=$CMD";
     eval $CMD;
     echo "eval of CMD is completed";
