name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  install:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [21, 25]
    runs-on: ${{ matrix.platform }}
    permissions:
      checks: write
      pull-requests: write
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 50

    - name: Setup local maven cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.m2/repository
        key: maven-cache-${{ hashFiles('**/pom.xml') }}

    - name: Set up JDKs
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: temurin
        java-version: |
          ${{ matrix.jdk }}

    - name: Build with Maven
      run: ./mvnw --errors --no-transfer-progress install

    - name: Difference Check
      run: ./.ci/validation.sh git-diff

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
      # we only want to attach test results one time, not for every matrix combination
      if: startsWith(matrix.platform, 'ubuntu') && (matrix.jdk == 21)
      with:
        files: '**/target/surefire-reports/*.xml'
