name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  install:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [17, 21]
    runs-on: ${{ matrix.platform }}
    permissions:
      checks: write
      pull-requests: write
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        fetch-depth: 50

    - name: Setup local maven cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ~/.m2/repository
        key: maven-cache-${{ hashFiles('**/pom.xml') }}

    - name: Set up JDKs
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: temurin
        # have Java 17 for Tycho last, as it will be in JAVA_HOME that way
        java-version: |
          ${{ matrix.jdk }}
          17

    - name: Build with Maven
      run: ./mvnw --errors --no-transfer-progress install

    - name: Difference Check
      run: ./.ci/validation.sh git-diff

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
      # we only want to attach test results one time, not for every matrix combination
      if: startsWith(matrix.platform, 'ubuntu') && (matrix.jdk == 17)
      with:
        files: '**/target/surefire-reports/*.xml'
